project_name: kanban
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/kanban
    binary: kanban
    ldflags:
      - -s -w -X github.com/shuntaka9576/kanban/cmd/kanban/cmd.Version={{.Version}} -X github.com/shuntaka9576/kanban/cmd/kanban/cmd.BuildDate={{time "2006-01-02"}}
    env:
      - CGO_ENABLED=0
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
